local map = require("theo.util.keymap")

map.n("<leader>pv", vim.cmd.Ex, "Open netrw")
map.n("<leader>nh", "<cmd>nohlsearch<cr>", "Clear search highlight")
map.n("<Esc>", "<cmd>nohlsearch<cr>", "Clear search highlight")
map.n("<leader>w", "<C-w>w", "Next window")
map.n("<leader>d", "<cmd>term mongosh<cr>i", "Open mongosh terminal")
map.n("<leader>q", vim.diagnostic.setloclist, "Open diagnostic list")
map.n("[d", function()
  vim.diagnostic.jump({ count = -1, float = true })
end, "Previous diagnostic")
map.n("]d", function()
  vim.diagnostic.jump({ count = 1, float = true })
end, "Next diagnostic")
